// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yskjguxaulvwwfnduytq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlza2pndXhhdWx2d3dmbmR1eXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MTQwMjAsImV4cCI6MjA1NzQ5MDAyMH0.BCZu9N7N6mvp_SruOR1MQOLnwLmeOJdTz6SR7brPMwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);